name: Main Action
run-name: Triggered by ${{ github.actor }} 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:lts
      env:
        NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      - name: Execution
        run: nodejs src/index.js
